language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run coverage
after_success: npm run report-coverage
notifications:
  slack: intelliware:mzyu8GqG4LOunucRTp6texaW
