language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_5644edef535c_key -iv $encrypted_5644edef535c_iv
  -in client-secret.json.enc -out client-secret.json -d
deploy:
  provider: gae
  keyfile: client-secret.json
  project: planning-poker
  skip_cleanup: true
  default: true
  on:
    branch: master
notifications:
  slack: intelliware:mzyu8GqG4LOunucRTp6texaW
